services: couchdb
language: java
install:
- curl -X PUT localhost:5984/test
- sudo pip install couchapp
- couchapp push . http://localhost:5984/test
- wget https://github.com/Hypertopic/Porphyry/archive/master.zip
- unzip master.zip
- cd Porphyry-master
- mkdir lib
script: ant test-argos
