services: docker

language: node_js

node_js: 10

cache:
  directories:
    - "node_modules"

install:
- npm run install:db
- npm run start:db
- npm install
- npm run populate:db
- npm run configure:db

script: npm test
