sudo: false

services: couchdb

language: node_js

node_js: 10

cache:
  directories:
    - "node_modules"

addons:
  hosts: argos.local

install:
- curl -X PUT localhost:5984/argos
- curl -X PUT -d '"false"' localhost:5984/_config/httpd/secure_rewrites
- curl -X PUT -d '"/argos/_design/argos/_rewrite"' localhost:5984/_config/vhosts/argos.local
- pip install --user couchapp
- couchapp pushdocs __tests__/api/fixtures  http://localhost:5984/argos
- couchapp push app http://localhost:5984/argos
- npm install

script: npm test
