services: docker

language: node_js

node_js: 10

cache:
  directories:
    - "node_modules"

install:
- docker pull benel/couchapp
- docker-compose up -d
- npm install
- npm run populate:db
- npm run configure:db

script: npm test
