services: docker

language: node_js

node_js: lts/*

cache:
  directories:
    - "node_modules"

install:
- docker-compose up -d running_infrastructure
- docker-compose run --rm push_docs
- docker-compose run --rm push_app
- npm install

script: npm test
