version: '3'

services:

  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
    logging:
      options:
        max-size: "1M"
        max-file: "3"
    restart: on-failure

  prod:
    image: benel/aaaforrest
    ports:
      - 80:1337
    volumes:
      - ./conf/aaaforrest.yml:/AAAforREST/conf/config.yml:ro
    working_dir: /AAAforREST
    restart: on-failure
    depends_on:
      - install
 
  test_data:
    image: benel/couchapp
    command: pushdocs .
    environment:
      - URI=http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/argos
    volumes:
      - ./__tests__/api/fixtures:/app
    depends_on:
      - install

  install:
    image: benel/couchapp
    command: push .
    environment:
      - URI=http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/argos
    volumes:
      - ./app:/app
    depends_on:
      - couchdb
