version: '3'

services:

  couchdb:
    image: couchdb
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
    logging:
      options:
        max-size: "1M"
        max-file: "3"
    restart: on-failure

  proxy:
    image: benel/aaaforrest
    ports:
      - 80:80
    volumes:
      - ./conf/aaaforrest.json:/AAAforREST/conf/config.json:ro
    working_dir: /AAAforREST
 
  running_infrastructure:
    image: dadarek/wait-for-dependencies
    command: couchdb:5984
    depends_on:
      - couchdb
      - proxy

  push_docs:
    image: benel/couchapp
    command: pushdocs . http://argos_couchdb_1:5984/argos
    volumes:
      - ./__tests__/api/fixtures:/app

  push_app:
    image: benel/couchapp
    command: push . http://argos_couchdb_1:5984/argos
    volumes:
      - ./app:/app
