name: Acceptance tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and run Argos with test data
        run: docker-compose up -d
      - name: Install test tools
        run: npm install
      - uses: nev7n/wait_for_response@v1
        with:
          url: http://localhost/
          responseCode: 200
      - name: Run tests
        run : npm test
        shell: 'script -q -e -c "bash {0}"'
